const services = [
    {
        id: 1,
        titulo: "Certificado de Aptitud Física",
        img: "/images/servicios/img1.png",
        li1: "Interrogatorio en búsqueda de factores de riesgo cardiovascular, antecedentes cardiovasculares personales o familiares.",
        li2: "Si surgiera algún dato anormal el medico le aconsejara la mejor forma de resolver la aptitud fisica.",
        li3: "Examen físico (peso talla, agudeza visual y vision fotocromatica aproximada).",
        li4: "El médico no esta obligado a emitir un certificado de aptitud física, si el paciente no está en condiciones saludables.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20evaluación%20cardiovascular",
    },
    {
        id: 2,
        titulo: "Certificado de Aptitud Psicofísica",
        img: "/images/servicios/img2.png",
        li1: "Interrogatorio en búsqueda de factores de riesgo cardiovascular.",
        li2: "Evaluación por teleconferencia con una licenciada en psicología.",
        li3: "Examen físico (peso talla, agudeza visual y vision fotocromatica aproximada).",
        li4: "El médico no esta obligado a emitir un certificado de aptitud física, si el paciente no está en condiciones saludables.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20evaluación%20cardiovascular",
    },   
    
    {
        id: 3,
        titulo: "Certificado de Aptitud Fisica Competitiva",
        img: "/images/servicios/img3.png",
        li1: "Interrogatorio en búsqueda de factores de riesgo cardiovascular.",
        li2: "Ergometria( Prueba Ergometrica Graduada).",
        li3: "Examen físico (peso talla, agudeza visual y vision fotocromatica aproximada, evaluación psicológica).",
        li4: "El médico no esta obligado a emitir un certificado de aptitud física, si el paciente no está en condiciones saludables.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20apto%20físico%20de%20alta%20competencia ",
    },

    {
        id: 4,
        titulo: "Especialista en Cardiología",
        img: "/images/servicios/img10.png",
        li1: "Interrogatorio en búsqueda de factores de riesgo cardiovascular, antecedentes cardiovasculares personales o familiares.",
        li2: "Lectura de estudios del paciente con su evaluación, revisión de la medicación habitual, y posteriores recomendaciones, segun lo que surja de la consulta.",
        li3: "Examen físico (peso talla, agudeza visual y vision fotocromatica aproximada).",
        li4: "El médico no esta obligado a emitir un certificado de aptitud física, si el paciente no está en condiciones saludables.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%apto%20físico",
    },
 
    {
        id: 5,
        titulo: "Especialista en Medicina Deportiva",
        img: "/images/servicios/img11.png",
        li1: "Apto físico completo. Orientacion en la recuperacion de lesiones y en el tipo de ejercicio o deporte. Desarrollo de buenos hábitos.",
        li2: "Medición de masa grasa - masa muscular y estudios que surjan durante la consulta. ",
        li3: "Es apropiado realizar una ergometria para medir la capacidad funcional, o estado físico , o estimar el consumo maximo de oxigeno.",
        li4: "Es apropiado una reevaluación a los 3 meses para ver los progresos del paciente",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20mapeo%20ambulatorio%20de%20presión%20arterial",
    },
    {
        id: 6,
        titulo: "Riesgo Quirúrgico Cardiovascular",
        img: "/images/servicios/img9.png",
        li1: "Interrogatorio en búsqueda de factores de riesgo cardiovascular, antecedentes cardiovasculares personales o familiares.",
        li2: "Emisión de constancia de medición de riesgo de sufrir un evento cardiovascular ante el estres de una cirugía no cardíaca",
        li3: "Posibles resultados: Habitual - Elevado - Muy elevado",
        li4: "Muy elevado: Requiere la presencia de un cardiologo en el momento de la cirugía con una eventual recuperación post operatoria en una Sala de Unidad Coronaria, o de Terapia Intensiva.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20prueba%20de%20esfuerzo%20graduada",
    },
    {
        id: 7,
        titulo: "Especialista en Electrofisiología y Marcapasos",
        img: "/images/servicios/img12.png",
        li1: "Interrogatorio en búsqueda de padecimientos de arritmias ya conocidas, sintomas de palpitaciones, perdidas de la conciencia inexplicables (sincopes)",
        li2: "Examen físico (peso talla, agudeza visual y vision fotocromatica aproximada).",
        li3: "Pacientes portadores de dispositivos intracardiacos",
        li4: "Se controlan todas las marcas con sus respectivos programadores. St Jude, Biotronik, Guidant, Boston Scientific, Medtronyk.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20Holter%20de%203%20canales",
    },
    {
        id: 8,
        titulo: "Ergometría Graduada de 12 canales",
        img: "/images/servicios/img5.png",
        li1: "Prueba de esfuerzo de 12 canales",
        li2: "Diagnóstico de patologías cardíacas asintomáticas en el reposo que se pueden diagnosticar en el esfuerzo",
        li3: "También mide la capacidad de ejercicio de una persona, para evaluar su progreso en un plan de entrenamiento, (mide el 100% de su capacidad de esfuerzo).",
        li4: "Se realiza en cicloergometro.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20control%20de%20marcapasos",
    },
    {
        id: 9,
        titulo: "Monitoreo Holter 3 canales (24hs)",
        img: "/images/servicios/img6.png",
        li1: "Estudio que graba 24 hs la actividad eléctrica del corazon",
        li2: "Contabiliza la cantidad de latidos normales, anormales, taquicardias y las bradicardia. Las agrupa y clasifica",
        li3: "El software debe ser de primera line, el estudio debe ser leido por un experto en arrtmias y marcapasos",
        li4: "Se indican para el estudio de palpitaciones, síncopes, evaluación de tratamiento con drogas antiarrítmicas  y control de pacientes que portan un marcapasos, o de pacientes que podrian llegar a necesitar el implante de uno.",
        wp: "https://wa.me/+541164977403?text=Hola, %20solicito%20información%20sobre%20electrocardiograma",
    },

    {
        id: 10,
        titulo: "Presurometria (24hs)",
        img: "/images/servicios/img4.png",
        li1: "Estudio fundamental para el correcto seguimiento y diagnostico del paciente con Hipertensión Arterial.",
        li2: "Registra los promedios de las cifras de las tomas de tensión arterial.",
        li3: "Evalua el patrón circadiano.",
        li4: "Se realiza un tratamiento en base a los resultados. ",
        wp: "https://wa.me/+541164977403?text=Hola, %20solicito%20información%20sobre%20electrocardiograma",
    },

    {
        id: 11,
        titulo: "Ecocardiograma Doppler o Doppler vascular",
        img: "/images/servicios/img8.png",
        li1: "Dispositivo de alta gama.",
        li4: "Los pacientes con una enfermedad cardiovascular ya diagnosticada deberia ser evaluados por este metodo",
        li3: "Indicado también para hipertensos, diabeticos, y fumadores, por el riesgo elevado de realizar cuadros coronarios",
        li2: "Profesional capacitado.",
        wp: "https://wa.me/+541164977403?text=Hola, %20solicito%20información%20sobre%20electrocardiograma",
    },

];

export default services;