const services = [
    {
        id: 1,
        titulo: "Evaluación Cardiovascular",
        img: "/images/servicios/img1.png",
        description: "Con un enfoque personalizado, te brindamos un diagnóstico preciso y recomendaciones preventivas para mantener un corazón fuerte y una vida plena.",
        li1: "Equipo de expertos",
        li2: "Exámenes exhaustivos",
        li3: "Diagnóstico preciso",
        li4: "Orientación y apoyo",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20evaluación%20cardiovascular",
    },
    {
        id: 2,
        titulo: "Apto Físico",
        img: "/images/servicios/img2.png",
        description: " Evaluamos tu salud cardiovascular y garantizar que estés en condiciones óptimas para realizar actividades físicas.",
        li1: "Evaluación cardiológica completa.",
        li2: "Asesoramiento y pautas seguras.",
        li3: "Enfoque integral.",
        li4: "Pruebas para detectar afecciones.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%apto%20físico",
    },
    {
        id: 3,
        titulo: "Apto Físico de Alta Competencia",
        img: "/images/servicios/img3.png",
        description: "Para atletas y deportistas de alta competencia, que buscan alcanzar su máximo rendimiento. Nos especializamos en medicina deportiva.",
        li1: "Evaluación cardiológica completa.",
        li2: "Tecnología avanzada.",
        li3: "Identificación temprana.",
        li4: "Planificación personalizada.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20apto%20físico%20de%20alta%20competencia ",
    },
    {
        id: 4,
        titulo: "Mapeo Ambulatorio de Presión Arterial",
        img: "/images/servicios/img4.png",
        description: "Monitoreo preciso y continuo de la presión arterial durante 24 horas. Brindando información vital para el diagnóstico y tratamiento de condiciones relacionadas con la presión arterial.",
        li1: "Registro automático  y preciso.",
        li2: "Análisis detallado de datos.",
        li3: "Evaluación de tratamientos.",
        li4: "Diagnóstico temprano.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20mapeo%20ambulatorio%20de%20presión%20arterial",
    },
    {
        id: 5,
        titulo: "Prueba de Esfuerzo Graduada",
        img: "/images/servicios/img5.png",
        description: "Fundamental para evaluar la respuesta del corazón durante el ejercicio. Brinda información clave para el diagnóstico de enfermedades cardíacas y la planificación de programas de entrenamiento.",
        li1: "Monitoreo preciso.",
        li2: "Seguimiento cercano.",
        li3: "Informe detallado.",
        li4: "Evaluación de capacidad cardiovascular.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20prueba%20de%20esfuerzo%20graduada",
    },
    {
        id: 6,
        titulo: "Holter 3 Canales",
        img: "/images/servicios/img6.png",
        description: "Técnica no invasiva que permite el monitoreo de la actividad eléctrica del corazón las 24 horas. Brinda información valiosa para el diagnóstico y tratamiento de arritmias y otros trastornos cardiacos.",
        li1: "Registro automático y preciso.",
        li2: "Evaluación minuciosa.",
        li3: "Dispositivo compacto y cómodo.",
        li4: "Informe completo y detallado.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20Holter%20de%203%20canales",
    },
    {
        id: 7,
        titulo: "Control de Marcapasos",
        img: "/images/servicios/img7.png",
        description: "Brindamos un seguimiento exhaustivo para garantizar un óptimo funcionamiento y rendimiento de estos dispositivos cardíacos.",
        li1: "Evaluación periódica.",
        li2: "Ajuste de programación de marcapasos.",
        li3: "Monitoreo constante.",
        li4: "Atención personalizada.",
        wp: "https://wa.me/+541164977403?text=Hola,%20solicito%20información%20sobre%20control%20de%20marcapasos",
    },
    {
        id: 8,
        titulo: "Electrocardiograma",
        img: "/images/servicios/img8.png",
        description: "Prueba no invasiva y rápida que permite evaluar la actividad eléctrica del corazón. Proporciona resultados precisos para el diagnóstico y seguimiento de condiciones cardiacas.",
        li1: "Registro detallado.",
        li2: "Resultados rápidos y confiables.",
        li3: "Ambiente cómodo.",
        li4: "Atención personalizada.",
        wp: "https://wa.me/+541164977403?text=Hola, %20solicito%20información%20sobre%20electrocardiograma",
    },

];

export default services;