const services = [
    {
        id: 1,
        titulo: "Evaluación Cardiovascular",
        img: "/images/servicios/img1.png",
        description: "Con un enfoque personalizado, te brindamos un diagnóstico preciso y recomendaciones preventivas para mantener un corazón fuerte y una vida plena.",
        li1: "Equipo de expertos",
        li2: "Exámenes exhaustivos",
        li3: "Diagnóstico preciso",
        li4: "Orientación y apoyo",
    },
    {
        id: 2,
        titulo: "Evaluación Cardiovascular",
        img: "/images/servicios/img1.png",
        description: "Con un enfoque personalizado, te brindamos un diagnóstico preciso y recomendaciones preventivas para mantener un corazón fuerte y una vida plena.",
        li1: "Equipo de expertos",
        li2: "Exámenes exhaustivos",
        li3: "Diagnóstico preciso",
        li4: "Orientación y apoyo",
    },
    {
        id: 3,
        titulo: "Evaluación Cardiovascular",
        img: "/images/servicios/img1.png",
        description: "Con un enfoque personalizado, te brindamos un diagnóstico preciso y recomendaciones preventivas para mantener un corazón fuerte y una vida plena.",
        li1: "Equipo de expertos",
        li2: "Exámenes exhaustivos",
        li3: "Diagnóstico preciso",
        li4: "Orientación y apoyo",
    },
    {
        id: 4,
        titulo: "Evaluación Cardiovascular",
        img: "/images/servicios/img1.png",
        description: "Con un enfoque personalizado, te brindamos un diagnóstico preciso y recomendaciones preventivas para mantener un corazón fuerte y una vida plena.",
        li1: "Equipo de expertos",
        li2: "Exámenes exhaustivos",
        li3: "Diagnóstico preciso",
        li4: "Orientación y apoyo",
    },
    {
        id: 5,
        titulo: "Evaluación Cardiovascular",
        img: "/images/servicios/img1.png",
        description: "Con un enfoque personalizado, te brindamos un diagnóstico preciso y recomendaciones preventivas para mantener un corazón fuerte y una vida plena.",
        li1: "Equipo de expertos",
        li2: "Exámenes exhaustivos",
        li3: "Diagnóstico preciso",
        li4: "Orientación y apoyo",
    },
    {
        id: 6,
        titulo: "Evaluación Cardiovascular",
        img: "/images/servicios/img1.png",
        description: "Con un enfoque personalizado, te brindamos un diagnóstico preciso y recomendaciones preventivas para mantener un corazón fuerte y una vida plena.",
        li1: "Equipo de expertos",
        li2: "Exámenes exhaustivos",
        li3: "Diagnóstico preciso",
        li4: "Orientación y apoyo",
    },
    {
        id: 7,
        titulo: "Evaluación Cardiovascular",
        img: "/images/servicios/img1.png",
        description: "Con un enfoque personalizado, te brindamos un diagnóstico preciso y recomendaciones preventivas para mantener un corazón fuerte y una vida plena.",
        li1: "Equipo de expertos",
        li2: "Exámenes exhaustivos",
        li3: "Diagnóstico preciso",
        li4: "Orientación y apoyo",
    },
    {
        id: 8,
        titulo: "Evaluación Cardiovascular",
        img: "/images/servicios/img1.png",
        description: "Con un enfoque personalizado, te brindamos un diagnóstico preciso y recomendaciones preventivas para mantener un corazón fuerte y una vida plena.",
        li1: "Equipo de expertos",
        li2: "Exámenes exhaustivos",
        li3: "Diagnóstico preciso",
        li4: "Orientación y apoyo",
    },

];

export default services;